source:       .
destination:  ./_site
layouts_dir:  _layouts
collections:
  fruits:
    output:   true # outputs page per item
  blog:
    output:   true # outputs page per item
plugins: [jekyll-polyglot]
baseurl: "/"
languages: ["en", "de"]
default_lang: "en"
parallel_localization: false